export const GET_PRODUCT_REQ = "GET_PRODUCT_REQ";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const SORT_DATA = "SORT_DATA";

export const GET_CLICKED_PRODUCT_REQ = "GET_CLICKED_PRODUCT_REQ";
export const GET_CLICKED_PRODUCT_SUCCESS = "GET_CLICKED_PRODUCT_SUCCESS";
export const GET_CLICKED_PRODUCT_FAILURE = "GET_CLICKED_PRODUCT_FAILURE";